config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do #:nodoc"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "cocktails#index"
  resources :cocktails, only: [:index, :show, :new, :create] do
    resources :doses, only: [:create]
    resources :reviews, only: [:create]
  end
  resources :doses, only: [:destroy]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base #:nodoc:
  self.abstract_class = true
end

app/models/cocktail.rb
# frozen_string_literal: true

class Cocktail < ApplicationRecord # :nodoc:
  validates :name, uniqueness: true, presence: true
  has_many :doses
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_many :reviews
end

app/models/dose.rb
# frozen_string_literal: true

class Dose < ApplicationRecord #:nodoc:
  validates :description, presence: true, allow_blank: false
  belongs_to :cocktail
  belongs_to :ingredient
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
# frozen_string_literal: true

class Ingredient < ApplicationRecord # :nodoc:
  has_many :cocktails, through: :doses
  has_many :doses
  validates :name, uniqueness: true, presence: true
end

app/models/review.rb
# frozen_string_literal: true

class Review < ApplicationRecord #:nodoc:
  belongs_to :cocktail
  validates :content, presence: true
  validates :rating, inclusion: { in: 0..5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
# frozen_string_literal: true

class CocktailsController < ApplicationController #:nodoc:
  def index
    @cocktails = Cocktail.all
  end

  def new
    @cocktail = Cocktail.new
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @dose = Dose.new
    @review = Review.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render 'new'
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :ingredient)
  end
end

app/controllers/doses_controller.rb
# frozen_string_literal: true

class DosesController < ApplicationController #:nodoc:

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      @review = Review.new
      render 'new'
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/controllers/reviews_controller.rb
# frozen_string_literal: true

class ReviewController < ApplicationController # :nodoc:
  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @review = Review.new(review_params)
    @review.cocktail = @cocktail
    if @review.save
      redirect_to cocktail_path(@cocktail)
    else
      @dose = Dose.new
      render 'cocktails/show'
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/review_helper.rb
module ReviewHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cocktails/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= image_path 'Bar.jpg' %>');">

  <div class="container-drinks">
  <div class="row">
    <% @cocktails.each do |cocktail| %>
      <div class="col-12 col-md-6 col-lg-3">
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.1), rgba(0,0,0,0.1)), url('<%= image_path 'amaretto_sour.png' %>');">
          <div class="card-description">
          </div>
            <%= link_to cocktail.name, cocktail_path(cocktail), class: 'card-link' %>
        </div>
      </div>
    <% end %>
  </div>
</div>
</div>

app/views/cocktails/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <h1>Create a new cocktail</h1>

      <%= simple_form_for @cocktail do |f| %>
        <%= f.input :name %>
        <%= f.input :photo, as: :file, label: "Photo" %>
        <%= f.button :submit, class: 'btn btn-success' %>
      <% end %>
    </div>
  </div>
</div>

app/views/cocktails/show.html.erb
  <h1><%= @cocktail.name %></h1>
  <%= link_to "Back to all cocktails", cocktails_path %>

  <div class="row">
    <div class="col-sm-12 col-md-6">
      <h3>Recipe</h3>
      <table class="table table-bordered">
        <tbody>
          <thead>
            <th>Ingredient</th>
            <th>Description</th>
            <th>Action</th>
          </thead>
          <% @cocktail.doses.each do |dose| %>
            <tr>
              <td><%= dose.ingredient.name %></td>
              <td><%= dose.description %></td>
              <td>
                <%= link_to dose_path(dose), method: :delete, data: { confirm: "Are you sure?" } do %>
                  <i class="fa fa-trash destroy_dose"></i>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-sm-12 col-md-6">
      <%= render "doses/new", cocktail: @cocktail, dose: @dose %>
    </div>
  </div>

  <h3>Reviews</h3>
  <% if @cocktail.reviews.empty? %>
    <p>Be the first to let a review</p>
  <% else %>
    <ul class="list-group">
      <% @cocktail.reviews.each do |review| %>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <span class="badge badge-primary badge-pill">
            <% counter = 0 %>
            <% 5.times do %>
              <i class="fa <%= review.rating > counter ? 'fa-star' : 'fa-star-o' %>"></i>
              <% counter += 1 %>
            <% end %>
          </span>
          <%= review.content %>
        </li>
      <% end %>
    </ul>
  <% end %>

  <%= render "reviews/new", cocktail: @cocktail, review: @review %>

app/views/doses/_new.html.erb
<h3>Add a new dose</h3>
<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.association :ingredient, input_html: { class: "beautiful-dropdown" }, include_hidden: false %>
  <%= f.input :description %>
  <%= f.button :submit, class: "btn btn-success" %>
<% end %>

app/views/doses/new.html.erb
<h3>Add a new dose</h3>
<%= simple_form_for [cocktail, dose] do |f| %>
  <%= f.association :ingredient, input_html: { class: "beautiful-dropdown" }, include_hidden: false %>
  <%= f.input :description %>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <div class="navbar navbar-expand-sm navbar-light navbar-susan">
  <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "SRCocktail.png" %>
  <% end %>

    <h1>Cocktailsium </h1>
      <h3>Handcrafted cocktails made with quality ingredients.</h3>


  <%= link_to "Add a Cocktail", new_cocktail_path, class: "btn btn-info btn-lg" %>

  </div>



  <body>
    <%= yield %>
    <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
    <%= javascript_pack_tag "application" %>
  </body>
  <div class="footer">
    <div class="footer-links">
      <a href="http://www.github.com/susan-renaud"><i class="fab fa-github"></i></a>
      <a href="https://www.instagram.com/susan_renaud/"><i class="fab fa-instagram"></i></a>
      <a href="https://www.facebook.com/profile.php?id=1530420089"><i class="fab fa-facebook"></i></a>
      <a href="https://www.linkedin.com/in/susanelizabethrenaud/"><i class="fab fa-linkedin"></i></a>
    </div>
    <div class="footer-copyright">
     This website was coded with <i class="fas fa-heart"></i> by Susan Renaud
    </div>
  </div>

</html>

app/views/review/_new.html.erb
<h3>Add a review</h3>
<%= simple_form_for [@cocktail, @review] do |f| %>
  <%= f.input :rating, collection: 0..5 %>
  <%= f.input :content %>
  <%= f.submit class: "btn btn-success"%>
<% end %>

app/views/reviews/_new.html.erb
<h3>Add a review</h3>
<%= simple_form_for [@cocktail, @review] do |f| %>
  <%= f.input :rating, collection: 0..5 %>
  <%= f.input :content %>
  <%= f.submit class: "btn btn-success"%>
<% end %>